version: "3.8"
services:
    react-app:
        # stdin_open: true
        # tty: true
        build: 
            context: .
            dockerfile: Dockerfile.prod
        ports:
            - "3001:80"
        env_file: 
            - ./.env


